dist: bionic

language: c++
sudo: false

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libxml2-dev
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -q update
  - sudo apt-get -y install gcc-4.8
  
compiler:
  - clang
  - gcc
  
deploy:
  skip_cleanup: true
  
